services:
  mongodb:
    image: mongo:4.4
    container_name: portfolio-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: portfolio
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./backend/data/mongodb:/data/db
