# Development environment
services:
  app:
    image: node:lts-alpine3.22
    container_name: meu-site-dev
    user: "1000:1000"
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://0.0.0.0:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
